name: Unittests
on: [push]
jobs:
  Unittests:
    name: Unittests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testOptSwitchTimes
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testOptSwitchTimes
      - name: testGetStopPos
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testGetStopPos

  GridTest:
    name: GridTest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: gridTestOneJoint
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests");
                   gridTestOneJoint