name: UnitTests
on: [push]
jobs:
  testOptBraking:
    name: testOptBraking
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testOptBraking
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testOptBraking

  testOptSwitchTimes:
    name: testOptSwitchTimes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testOptSwitchTimes
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testOptSwitchTimes

  testTimeScaling:
    name: testTimeScaling
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testTimeScaling
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testTimeScaling