name: UnitTests
on: [push]
jobs:
  testGetStopPos:
    name: testGetStopPos
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testGetStopPos
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testGetStopPos

  testOptSwitchTimes:
    name: testOptSwitchTimes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: testOptSwitchTimes
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("tests/unittests");
                   testOptSwitchTimes